apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-todo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-todo
  template:
    metadata:
      labels:
        app: front-todo
    spec:
      containers:
      - name: front-todo
        image: manassehrandriamitsiry/front-todo:0.1.0
        ports:
        - containerPort: 80
